### ISSUE TITLE
serial communication

### ISSUE THREAD

**Issue by hojun-lee99** [CEUKIE/ckie-hw#2]
## 작업 사항
* 아두이노 uno와 esp-32에 시리얼 통신 기능을 추가한다

## To-do

- [x] 시리얼 통신 구현
- [x] 최대최소 온습도 송수신
- [x] 현재 온습도 송수신
